apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - rbac.yaml
  - certificate.yaml
  - service.yaml
  - deployment.yaml
  - webhook.yaml
  - image-automation.yaml
