apiVersion: v1
kind: Service
metadata:
  name: keyvault-operator-metrics
  namespace: keyvault-system
  labels:
    app.kubernetes.io/name: keyvault-operator
spec:
  selector:
    control-plane: controller-manager
    app.kubernetes.io/name: keyvault-operator
  ports:
    - name: https
      port: 8443
      protocol: TCP
      targetPort: 8443
