apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cloud-ui
  namespace: dc-system
  annotations:
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
spec:
  ingressClassName: nginx
  tls:
    - hosts: ["cloud.placeholder.example.com"]
      secretName: dc-api-tls
  rules:
    - host: cloud.placeholder.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: cloud-ui
                port: { number: 80 }
