# ── Standardized OIDC interface (shared by all provider modules) ──────────────

output "client_id" {
  value       = asgardeo_application.this.client_id
  description = "OAuth2 client ID generated by Asgardeo."
}

output "client_secret" {
  value       = asgardeo_application.this.client_secret
  description = "OAuth2 client secret generated by Asgardeo."
  sensitive   = true
}

output "issuer_url" {
  value       = local.issuer_url
  description = "OIDC issuer URL (token endpoint used as issuer for Rancher compatibility)."
}

output "auth_endpoint" {
  value       = local.auth_endpoint
  description = "OAuth2 authorization endpoint."
}

output "token_endpoint" {
  value       = local.token_endpoint
  description = "OAuth2 token endpoint."
}

output "jwks_url" {
  value       = local.jwks_url
  description = "JSON Web Key Set URL for token signature verification."
}

# ── Asgardeo-specific outputs ─────────────────────────────────────────────────

output "application_id" {
  value       = asgardeo_application.this.id
  description = "Asgardeo internal application ID."
}

output "discovery_url" {
  value       = local.discovery_url
  description = "OIDC well-known discovery URL for manual verification."
}
