//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.
// Regenerate with: controller-gen object:headerFile="hack/boilerplate.go.txt" paths="./..."

package v1alpha1

import (
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// ── BackendRef ───────────────────────────────────────────────────────────────

func (in *BackendRef) DeepCopyInto(out *BackendRef) {
	*out = *in
}

func (in *BackendRef) DeepCopy() *BackendRef {
	if in == nil {
		return nil
	}
	out := new(BackendRef)
	in.DeepCopyInto(out)
	return out
}

// ── RegistryBackend ──────────────────────────────────────────────────────────

func (in *RegistryBackend) DeepCopyInto(out *RegistryBackend) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

func (in *RegistryBackend) DeepCopy() *RegistryBackend {
	if in == nil {
		return nil
	}
	out := new(RegistryBackend)
	in.DeepCopyInto(out)
	return out
}

func (in *RegistryBackend) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *RegistryBackendList) DeepCopyInto(out *RegistryBackendList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]RegistryBackend, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

func (in *RegistryBackendList) DeepCopy() *RegistryBackendList {
	if in == nil {
		return nil
	}
	out := new(RegistryBackendList)
	in.DeepCopyInto(out)
	return out
}

func (in *RegistryBackendList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *RegistryBackendSpec) DeepCopyInto(out *RegistryBackendSpec) {
	*out = *in
}

func (in *RegistryBackendSpec) DeepCopy() *RegistryBackendSpec {
	if in == nil {
		return nil
	}
	out := new(RegistryBackendSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *RegistryBackendStatus) DeepCopyInto(out *RegistryBackendStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Progress != nil {
		in, out := &in.Progress, &out.Progress
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

func (in *RegistryBackendStatus) DeepCopy() *RegistryBackendStatus {
	if in == nil {
		return nil
	}
	out := new(RegistryBackendStatus)
	in.DeepCopyInto(out)
	return out
}

// ── RegistryInstance ─────────────────────────────────────────────────────────

func (in *RegistryInstance) DeepCopyInto(out *RegistryInstance) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

func (in *RegistryInstance) DeepCopy() *RegistryInstance {
	if in == nil {
		return nil
	}
	out := new(RegistryInstance)
	in.DeepCopyInto(out)
	return out
}

func (in *RegistryInstance) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *RegistryInstanceList) DeepCopyInto(out *RegistryInstanceList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]RegistryInstance, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

func (in *RegistryInstanceList) DeepCopy() *RegistryInstanceList {
	if in == nil {
		return nil
	}
	out := new(RegistryInstanceList)
	in.DeepCopyInto(out)
	return out
}

func (in *RegistryInstanceList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *RegistryInstanceSpec) DeepCopyInto(out *RegistryInstanceSpec) {
	*out = *in
	out.BackendRef = in.BackendRef
}

func (in *RegistryInstanceSpec) DeepCopy() *RegistryInstanceSpec {
	if in == nil {
		return nil
	}
	out := new(RegistryInstanceSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *RegistryInstanceStatus) DeepCopyInto(out *RegistryInstanceStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Progress != nil {
		in, out := &in.Progress, &out.Progress
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

func (in *RegistryInstanceStatus) DeepCopy() *RegistryInstanceStatus {
	if in == nil {
		return nil
	}
	out := new(RegistryInstanceStatus)
	in.DeepCopyInto(out)
	return out
}
