apiVersion: registry.opencloud.wso2.com/v1alpha1
kind: RegistryBackend
metadata:
  labels:
    app.kubernetes.io/name: registry
    app.kubernetes.io/managed-by: kustomize
  name: registrybackend-sample
spec: {}
