apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argo

resources:
  - rbac.yaml
  - workflow-template.yaml

configurations:
  - kustomizeconfig.yaml

images:
  - name: cap-002-terraform-runner
    newName: ghcr.io/yohansenanayake/harvester-testsuite
    digest: sha256:d616914702b92ed26e85771abff2b1136f8a917532d38bd1f2ed00855fa53165
    
